### PR TITLE
Recompile for KSP 1.3.1

### PR DESCRIPTION
**Pull request by aw1621107**
Make sure you have read and understood the contributing guidelines!
-------------------------------------------------------------------

Pull Requests that don't follow the guidelines will be rejected.  If you need help or are confused just ask, and we will be glad to help.

- [x] PR being applied to the correct **Feature Branch** or **dev**
- [x] PR is **not** being sent to **master**

### CODE REVIEW

**Comment by jwvanderbeck** [comment]
Don't forget to merge this back to master before you cut the release.  I'd suggest releasing it as 1.9 or even 2.0.

Thanks for keeping this going!

**Comment by jwvanderbeck** [comment]
Looks like this never got acted on.  You guys shouldn't need me to do merges and releases.  If you have permissions and everything has been checked then feel free to do it on your own.

**Comment by NathanKell** [comment]
@jwvanderbeck Yep, but I was also gone and IIRC awang didn't have the perms. However I'm fixing *both* of those issues :)

**Comment by jwvanderbeck** [comment]
Thanks!

**Pull request merged**
