### PR TITLE
Update for ksp 1.5.1

### PR DESCRIPTION
**Pull request by aw1621107**
Make sure you have read and understood the contributing guidelines!
-------------------------------------------------------------------

Pull Requests that don't follow the guidelines will be rejected.  If you need help or are confused just ask, and we will be glad to help.

- [x] PR being applied to the correct **Feature Branch** or **dev**
- [x] PR is **not** being sent to **master**

### CODE REVIEW

**Comment by Bornholio** [comment]
is this depending on #181 changes?

**Comment by aw1621107** [comment]
@Bornholio This shouldn't depend on #181 because that is asking to merge the dev branch into master, but this PR is adding to the dev branch

**Comment by Bornholio** [comment]
Finally got around to a full 1.4.5 RP-1 install.  TF using these updates.  I'll give a bit more feedback after teh weekend but it all seems good so far.  @aw1621107 can you say if there are any extra features that need to be tested.

**Comment by aw1621107** [comment]
@Bornholio I didn't add any features myself when recompiling, at least

**Comment by Bornholio** [comment]
did forty sounding rocket launches among other things and had normal agathorn things happen.  
Seems Good to go.

**Comment by Bornholio** [comment]
@aw1621107 the color coded stability stage icons are not in this one.  That change was "AWESOME"  is that stuck on your other comp?

**Comment by jwvanderbeck** [comment]
Fuel stability colored icons are RF
TF only changes the icon color on engines if they fail.  Yellow for a minor failure (Efficiency failure for example) and red for a major failure.

**Comment by Bornholio** [comment]
ah yes you're right.  RF.  wonder why i'm missing that change.

**Comment by 7ranceaddic7** [comment]
YeAh!  When is this bad boy rolling out?  I've been waiting patiently for this one.

**Comment by 7ranceaddic7** [comment]
Wait, you just blew right past a 1.4.5 recompile?

**Comment by aw1621107** [comment]
@7ranceaddic7 I guess?

**Comment by pap1723** [comment]
Too much has taken place for this to work. We will be releasing for 1.6.1+ soon

**Pull request closed without merging**
